apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-storage-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: /opt/backups
    type: DirectoryOrCreate
