apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Adjust based on your needs
