apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  namespace: backups
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  resources:
    requests:
      storage: 50Gi
