apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: backups
data:
  backup.sh: |
    #!/bin/bash
    set -e
    
    # Configuration
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_DIR="/backups"
    DB_HOST="postgresql.postgresql.svc.cluster.local"
    DB_PORT="5432"
    DB_USER="odoo"
    DB_NAME="postgres"
    ODOO_DATA_DIR="/odoo-data"
    RETENTION_DAYS=7
    
    echo "🔄 Starting COMPLETE backup at $(date)"
    echo "================================================"
    
    # Create backup directory
    mkdir -p ${BACKUP_DIR}/${TIMESTAMP}
    
    # 1. Backup all Odoo databases individually
    echo "📦 [1/3] Backing up Odoo databases..."
    
    # Get list of Odoo databases (exclude postgres, template0, template1)
    DATABASES=$(PGPASSWORD=${POSTGRES_PASSWORD} psql \
      -h ${DB_HOST} \
      -p ${DB_PORT} \
      -U ${DB_USER} \
      -d postgres \
      -t -c "SELECT datname FROM pg_database WHERE datname NOT IN ('postgres', 'template0', 'template1');" | grep -v '^$')
    
    if [ -z "$DATABASES" ]; then
        echo "   ⚠️  No Odoo databases found to backup"
    else
        mkdir -p ${BACKUP_DIR}/${TIMESTAMP}/databases
        for DB in $DATABASES; do
            DB_CLEAN=$(echo $DB | xargs)  # Remove whitespace
            echo "   📦 Backing up database: ${DB_CLEAN}..."
            PGPASSWORD=${POSTGRES_PASSWORD} pg_dump \
              -h ${DB_HOST} \
              -p ${DB_PORT} \
              -U ${DB_USER} \
              -d ${DB_CLEAN} \
              -F c \
              -f ${BACKUP_DIR}/${TIMESTAMP}/databases/${DB_CLEAN}.dump
            
            DB_SIZE=$(du -h ${BACKUP_DIR}/${TIMESTAMP}/databases/${DB_CLEAN}.dump | cut -f1)
            echo "      ✅ ${DB_CLEAN}: ${DB_SIZE}"
        done
    fi
    
    # 2. Backup Odoo filestore (if exists)
    if [ -d "${ODOO_DATA_DIR}/filestore" ]; then
        echo "📁 [2/3] Backing up Odoo filestore..."
        tar -czf ${BACKUP_DIR}/${TIMESTAMP}/filestore.tar.gz \
          -C ${ODOO_DATA_DIR} filestore/
        
        FS_SIZE=$(du -h ${BACKUP_DIR}/${TIMESTAMP}/filestore.tar.gz | cut -f1)
        echo "   ✅ Filestore backup: ${FS_SIZE}"
    else
        echo "⚠️  [2/3] Odoo filestore not found, skipping..."
    fi
    
    # 3. Backup Odoo sessions (optional)
    if [ -d "${ODOO_DATA_DIR}/sessions" ]; then
        echo "💾 [3/3] Backing up Odoo sessions..."
        tar -czf ${BACKUP_DIR}/${TIMESTAMP}/sessions.tar.gz \
          -C ${ODOO_DATA_DIR} sessions/
        echo "   ✅ Sessions backup completed"
    else
        echo "ℹ️  [3/3] Sessions not found, skipping..."
    fi
    
    # Create backup manifest
    echo "📝 Creating backup manifest..."
    cat > ${BACKUP_DIR}/${TIMESTAMP}/manifest.txt <<EOF
Backup Date: $(date)
Timestamp: ${TIMESTAMP}
Databases: $(echo $DATABASES | wc -w) Odoo database(s)
Database Names: ${DATABASES}
Filestore Size: ${FS_SIZE:-N/A}
Odoo Version: 19.0
PostgreSQL Version: 17
EOF
    
    # Compress complete backup
    echo "📦 Compressing complete backup..."
    cd ${BACKUP_DIR}
    tar -czf ${TIMESTAMP}_complete.tar.gz ${TIMESTAMP}/
    rm -rf ${TIMESTAMP}/
    
    # Calculate total backup size
    TOTAL_SIZE=$(du -h ${TIMESTAMP}_complete.tar.gz | cut -f1)
    echo ""
    echo "✅ COMPLETE backup finished: ${TIMESTAMP}_complete.tar.gz"
    echo "   Total size: ${TOTAL_SIZE}"
    echo "   Contents: Individual Databases + Filestore + Sessions + Manifest"
    
    # Clean old backups
    echo ""
    echo "🧹 Cleaning backups older than ${RETENTION_DAYS} days..."
    find ${BACKUP_DIR} -name "*_complete.tar.gz" -type f -mtime +${RETENTION_DAYS} -delete
    
    # List current backups
    echo ""
    echo "📋 Current backups:"
    ls -lh ${BACKUP_DIR}/*_complete.tar.gz 2>/dev/null || echo "No backups found"
    
    echo ""
    echo "✅ Backup process completed at $(date)"
    echo "================================================"
