apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: backups
data:
  backup.sh: |
    #!/bin/bash
    set -e
    
    # Configuration
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_DIR="/backups"
    DB_HOST="postgresql.postgresql.svc.cluster.local"
    DB_PORT="5432"
    DB_USER="odoo"
    DB_NAME="postgres"
    ODOO_DATA_DIR="/odoo-data"
    RETENTION_DAYS=7
    
    echo "ðŸ”„ Starting COMPLETE backup at $(date)"
    echo "================================================"
    
    # Create backup directory
    mkdir -p ${BACKUP_DIR}/${TIMESTAMP}
    
    # 1. Backup PostgreSQL database
    echo "ðŸ“¦ [1/3] Backing up PostgreSQL database..."
    PGPASSWORD=${POSTGRES_PASSWORD} pg_dump \
      -h ${DB_HOST} \
      -p ${DB_PORT} \
      -U ${DB_USER} \
      -d ${DB_NAME} \
      -F c \
      -f ${BACKUP_DIR}/${TIMESTAMP}/database.dump
    
    DB_SIZE=$(du -h ${BACKUP_DIR}/${TIMESTAMP}/database.dump | cut -f1)
    echo "   âœ… Database backup: ${DB_SIZE}"
    
    # 2. Backup Odoo filestore (if exists)
    if [ -d "${ODOO_DATA_DIR}/filestore" ]; then
        echo "ðŸ“ [2/3] Backing up Odoo filestore..."
        tar -czf ${BACKUP_DIR}/${TIMESTAMP}/filestore.tar.gz \
          -C ${ODOO_DATA_DIR} filestore/
        
        FS_SIZE=$(du -h ${BACKUP_DIR}/${TIMESTAMP}/filestore.tar.gz | cut -f1)
        echo "   âœ… Filestore backup: ${FS_SIZE}"
    else
        echo "âš ï¸  [2/3] Odoo filestore not found, skipping..."
    fi
    
    # 3. Backup Odoo sessions (optional)
    if [ -d "${ODOO_DATA_DIR}/sessions" ]; then
        echo "ðŸ’¾ [3/3] Backing up Odoo sessions..."
        tar -czf ${BACKUP_DIR}/${TIMESTAMP}/sessions.tar.gz \
          -C ${ODOO_DATA_DIR} sessions/
        echo "   âœ… Sessions backup completed"
    else
        echo "â„¹ï¸  [3/3] Sessions not found, skipping..."
    fi
    
    # Create backup manifest
    echo "ðŸ“ Creating backup manifest..."
    cat > ${BACKUP_DIR}/${TIMESTAMP}/manifest.txt <<EOF
Backup Date: $(date)
Timestamp: ${TIMESTAMP}
Database: ${DB_NAME}
Database Size: ${DB_SIZE}
Filestore Size: ${FS_SIZE:-N/A}
Odoo Version: 19.0
PostgreSQL Version: 17
EOF
    
    # Compress complete backup
    echo "ðŸ—œï¸  Compressing complete backup..."
    cd ${BACKUP_DIR}
    tar -czf ${TIMESTAMP}_complete.tar.gz ${TIMESTAMP}/
    rm -rf ${TIMESTAMP}/
    
    # Calculate total backup size
    TOTAL_SIZE=$(du -h ${TIMESTAMP}_complete.tar.gz | cut -f1)
    echo ""
    echo "âœ… COMPLETE backup finished: ${TIMESTAMP}_complete.tar.gz"
    echo "   Total size: ${TOTAL_SIZE}"
    echo "   Contents: Database + Filestore + Sessions + Manifest"
    
    # Clean old backups
    echo ""
    echo "ðŸ§¹ Cleaning backups older than ${RETENTION_DAYS} days..."
    find ${BACKUP_DIR} -name "*_complete.tar.gz" -type f -mtime +${RETENTION_DAYS} -delete
    
    # List current backups
    echo ""
    echo "ðŸ“‹ Current backups:"
    ls -lh ${BACKUP_DIR}/*_complete.tar.gz 2>/dev/null || echo "No backups found"
    
    echo ""
    echo "âœ… Backup process completed at $(date)"
    echo "================================================"
