apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: backups
data:
  backup.sh: |
    #!/bin/bash
    set -e
    
    # Configuration
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_DIR="/backups"
    DB_HOST="postgresql.postgresql.svc.cluster.local"
    DB_PORT="5432"
    DB_USER="odoo"
    DB_NAME="postgres"
    ODOO_DATA_DIR="/odoo-data"
    RETENTION_DAYS=7
    
    echo "ðŸ”„ Starting COMPLETE backup at $(date)"
    echo "================================================"
    
    # 1. Backup all Odoo databases individually
    echo "ðŸ“¦ [1/1] Backing up Odoo databases..."
    
    # Get list of Odoo databases (exclude postgres, template0, template1)
    DATABASES=$(PGPASSWORD=${POSTGRES_PASSWORD} psql \
      -h ${DB_HOST} \
      -p ${DB_PORT} \
      -U ${DB_USER} \
      -d postgres \
      -t -c "SELECT datname FROM pg_database WHERE datname NOT IN ('postgres', 'template0', 'template1');" | grep -v '^$')
    
    if [ -z "$DATABASES" ]; then
        echo "   âš ï¸  No Odoo databases found to backup"
    else
        for DB in $DATABASES; do
            DB_CLEAN=$(echo $DB | xargs)  # Remove whitespace
            echo "   ðŸ“¦ Backing up database: ${DB_CLEAN}..."
            
            # Create temporary directory for this database
            TEMP_DIR="${BACKUP_DIR}/temp_${DB_CLEAN}_${TIMESTAMP}"
            mkdir -p ${TEMP_DIR}
            
            # Backup database
            PGPASSWORD=${POSTGRES_PASSWORD} pg_dump \
              -h ${DB_HOST} \
              -p ${DB_PORT} \
              -U ${DB_USER} \
              -d ${DB_CLEAN} \
              -F c \
              -f ${TEMP_DIR}/database.dump
            
            DB_SIZE=$(du -h ${TEMP_DIR}/database.dump | cut -f1)
            echo "      âœ… Database: ${DB_SIZE}"
            
            # Backup filestore for this database (if exists)
            if [ -d "${ODOO_DATA_DIR}/filestore/${DB_CLEAN}" ]; then
                echo "      ðŸ“ Backing up filestore..."
                tar -czf ${TEMP_DIR}/filestore.tar.gz \
                  -C ${ODOO_DATA_DIR}/filestore ${DB_CLEAN}/
                FS_SIZE=$(du -h ${TEMP_DIR}/filestore.tar.gz | cut -f1)
                echo "         âœ… Filestore: ${FS_SIZE}"
            fi
            
            # Create manifest for this database
            echo "Backup Date: $(date)" > ${TEMP_DIR}/manifest.txt
            echo "Timestamp: ${TIMESTAMP}" >> ${TEMP_DIR}/manifest.txt
            echo "Database: ${DB_CLEAN}" >> ${TEMP_DIR}/manifest.txt
            echo "Odoo Version: 19.0" >> ${TEMP_DIR}/manifest.txt
            echo "PostgreSQL Version: 17" >> ${TEMP_DIR}/manifest.txt
            
            # Create directory for this database
            mkdir -p ${BACKUP_DIR}/${DB_CLEAN}
            
            # Compress this database backup
            echo "      ðŸ“¦ Compressing..."
            cd ${BACKUP_DIR}
            tar -czf ${DB_CLEAN}/${TIMESTAMP}.tar.gz -C ${TEMP_DIR} .
            rm -rf ${TEMP_DIR}
            
            BACKUP_SIZE=$(du -h ${DB_CLEAN}/${TIMESTAMP}.tar.gz | cut -f1)
            echo "      âœ… Backup created: ${DB_CLEAN}/${TIMESTAMP}.tar.gz (${BACKUP_SIZE})"
        done
    fi
    
    echo ""
    echo "âœ… Backup process completed!"
    echo "   $(echo $DATABASES | wc -w) database(s) backed up"
    
    # Clean old backups
    echo ""
    echo "ðŸ§¹ Cleaning backups older than ${RETENTION_DAYS} days..."
    find ${BACKUP_DIR} -name "*.tar.gz" -type f -mtime +${RETENTION_DAYS} -delete
    
    # List current backups
    echo ""
    echo "ðŸ“‹ Current backups by database:"
    for DB_DIR in ${BACKUP_DIR}/*/; do
        if [ -d "$DB_DIR" ]; then
            DB_NAME=$(basename "$DB_DIR")
            echo "  ðŸ“ ${DB_NAME}:"
            ls -lh ${DB_DIR}*.tar.gz 2>/dev/null | awk '{print "     " $9 " (" $5 ")"}'
        fi
    done
    
    echo ""
    echo "âœ… Backup process completed at $(date)"
    echo "================================================"
