apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: /opt/postgresql-data
    type: DirectoryOrCreate
