apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: postgresql
type: Opaque
data:
  # Default: odoo (base64 encoded)
  # To change: echo -n "your-password" | base64
  postgres-password: b2Rvbw==
  postgres-user: b2Rvbw==
  postgres-db: cG9zdGdyZXM=
