apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo
data:
  odoo.conf: |
    [options]
    admin_passwd = ${ODOO_ADMIN_PASSWD}
    db_host = postgresql.postgresql.svc.cluster.local
    db_port = 5432
    db_user = odoo
    db_password = odoo
    addons_path = /mnt/extra-addons
    data_dir = /var/lib/odoo
    proxy_mode = True
    
    # Performance Configuration
    workers = 4
    max_cron_threads = 2
    
    # Gevent mode for better concurrency
    server_wide_modules = base,web
    
    # Limits
    limit_memory_hard = 2684354560
    limit_memory_soft = 2147483648
    limit_request = 8192
    limit_time_cpu = 600
    limit_time_real = 1200
    limit_time_real_cron = 0
